apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubernetes-network
  namespace: functionality-test
spec:
  selector:
    matchLabels:
      name: kubernetes-network
  template:
    metadata:
      labels:
        name: kubernetes-network
    spec:
      volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig
            defaultMode: 420
      containers:
        - name: kubernetes-network
          image: mormoroth/kubernetes-network-test:latest
          resources: {}
          volumeMounts:
            - name: kubeconfig
              mountPath: /app
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10