---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-nodes-pinger
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubernetes-nodes-pinger
  namespace: kubernetes-nodes-pinger
  labels:
    name: kubernetes-nodes-pinger
spec:
  selector:
    matchLabels:
      name: kubernetes-nodes-pinger
  template:
    metadata:
      labels:
        name: kubernetes-nodes-pinger
    spec:
      volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig
            defaultMode: 420
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: kubernetes-nodes-pinger
          image: mormoroth/kubernetes-nodes-pinger:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: kubeconfig
              mountPath: /app/config
          imagePullPolicy: Always
      restartPolicy: Always
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-nodes-pinger
  namespace: kubernetes-nodes-pinger
  labels:
    name: kubernetes-nodes-pinger
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    name: kubernetes-nodes-pinger
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig
  namespace: kubernetes-nodes-pinger
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: 
        server: https://127.0.0.1:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kubernetes-admin
      name: kubernetes-admin@kubernetes
    current-context: kubernetes-admin@kubernetes
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: 
        client-key-data: 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-nodes-pinger
  namespace: kubernetes-nodes-pinger
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kubernetes-nodes-pinger.cluster.morteza.dev
      secretName: kubernetes-nodes-pinger-prod
  rules:
    - host: kubernetes-nodes-pinger.cluster.morteza.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-nodes-pinger
                port:
                  number: 80
